# Linear Algebra for ML

### Week 2 - Day 3

In this notebook, we will cover:
1. Represent three data **samples** as a (3 × **features**) NumPy **matrix**.
2. Compute the **dot product** of one sample **vector** with a weight vector by hand, then verify it with
np.dot.
3. Use **matrix multiplication** (@) to produce a prediction for all three samples at once.
4.  Deliberately create a shape-mismatch error, read the message, and explain in Markdown why it
occurred and how to fix it.
> Note: Words written in bold represents key topics that were studied and covered during the day.

In [1]:
import numpy as np

### Step 1 - Represent three data samples as a matrix:

In [7]:
x = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print("X =\n", x)
print("Shape of X:", x.shape, "3 Samples, 3 featuers")

X =
 [[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]
Shape of X: (3, 3) 3 Samples, 3 featuers


### Step 2 - Dot product:

In [10]:
features = x[0]                         # [25, 50000, 3]
weights = np.array([0.1, 0.0002, 1.5])  

# By Hand:
by_hand = (features[0] * weights[0]) +  (features[1] * weights[1]) + (features[2] * weights[2])
print("By hand:", by_hand)

# Verifiy with np.dot:
verified = np.dot(features, weights)
print("np.dot:", by_hand)

By hand: 17.0
np.dot: 17.0


### Step 3 - Matrix multiplication:

In [11]:
predictions = x @ weights

print("X Shape:", x.shape)
print("Weights Shape:", weights.shape)
print("Predictions:", predictions)

for i, pred in enumerate(predictions):
    print(f"Customer {i+1}: predicted score = {pred:.2f}")

X Shape: (3, 3)
Weights Shape: (3,)
Predictions: [17.  35.  23.2]
Customer 1: predicted score = 17.00
Customer 2: predicted score = 35.00
Customer 3: predicted score = 23.20


### Step 4 — Deliberately a shape-mismatch:

In [13]:
bad_weights = np.array([0.1, 0.0002, 1.5, 0.9])

try:
    broken = x @ bad_weights
except ValueError as e:
    print("ValueError raised:")
    print(e)

ValueError raised:
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)


> Note: Every cell of above is explaied by markdown or by comments.